---
- name: Применить sysctl сетевого шлюза
  ansible.builtin.command:
    argv:
      - sysctl
      - --system
  changed_when: true

- name: Перезапустить nftables
  ansible.builtin.systemd:
    name: nftables
    state: restarted
