schema_version: 11
vmid: 310
name: dev-services
profile: debian-lxc-docker

description: Службы хранения исходного кода, сборки и разработки

resources:
  cores: 2
  memory_mb: 4096
  swap_mb: 1024
  disk_size_gb: 32
