schema_version: 11
vmid: 100
name: haos
node: pve

description: Current production Home Assistant OS VM migrated from Raspberry Pi

resources:
  cores: 2
  memory_mb: 4096
  ballooning_mb: 2048
  disk_size_gb: 32
  disk_storage: local-lvm

boot:
  onboot: true
