schema_version: 11
vmid: 211
name: automation-services
profile: debian-lxc-docker

description: MQTT, Zigbee2MQTT and ESPHome infrastructure services

resources:
  cores: 2
  memory_mb: 2048
  swap_mb: 512
  disk_size_gb: 16
