schema_version: 12
vmid: 109
name: network-gateway
profile: debian-vm

description: Network gateway, DNS, VPN and policy routing

resources:
  cores: 2
  memory_mb: 2048
  disk_size_gb: 16

network:
  interfaces:
    - name: wan
      bridge: vmbr0
      vlan: 10
      ipv4: 10.0.0.2/30
      gateway: 10.0.0.1

    - name: lan
      bridge: vmbr0
      vlan: 20
      ipv4: 192.168.1.9/16
      management: true
