$schema: https://json-schema.org/draft/2020-12/schema
$title: Guest status definition
$ref: '#/$defs/commonStatus'

$defs:
  commonStatus:
    type: object
    additionalProperties: false
    required:
      - schema_version
      - guest_vmid
      - checks
    properties:
      schema_version:
        const: 2
      guest_vmid:
        type: integer
        minimum: 100
        maximum: 999
      checks:
        type: array
        minItems: 1
        items:
          oneOf:
            - $ref: '#/$defs/dockerCheck'
            - $ref: '#/$defs/fileCheck'
            - $ref: '#/$defs/httpCheck'
            - $ref: '#/$defs/localStatusCheck'
            - $ref: '#/$defs/systemdCheck'
            - $ref: '#/$defs/tcpCheck'

  dockerCheck:
    type: object
    additionalProperties: false
    required: [type, message, container]
    properties:
      type:
        const: docker
      message:
        type: string
        minLength: 1
      container:
        type: string
        minLength: 1

  fileCheck:
    type: object
    additionalProperties: false
    required: [type, message, path]
    properties:
      type:
        const: file
      message:
        type: string
        minLength: 1
      path:
        type: string
        pattern: '^/'

  httpCheck:
    type: object
    additionalProperties: false
    required: [type, message, url]
    properties:
      type:
        const: http
      message:
        type: string
        minLength: 1
      url:
        type: string
        minLength: 1

  localStatusCheck:
    type: object
    additionalProperties: false
    required: [type, message, command]
    properties:
      type:
        const: local_status
      message:
        type: string
        minLength: 1
      command:
        type: string
        pattern: '^/'

  systemdCheck:
    type: object
    additionalProperties: false
    required: [type, message, unit]
    properties:
      type:
        const: systemd
      message:
        type: string
        minLength: 1
      unit:
        type: string
        minLength: 1

  tcpCheck:
    type: object
    additionalProperties: false
    required: [type, message, port]
    properties:
      type:
        const: tcp
      message:
        type: string
        minLength: 1
      port:
        type: integer
        minimum: 1
        maximum: 65535
